name: Build and Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    # Setup Google Cloud SDK
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCLOUD_PROJECT }}
        service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}

    - name: Authenticate Docker with Google Cloud
      run: |
        gcloud auth configure-docker gcr.io

    # Debug Docker Authentication    
    - name: Debug Docker Authentication
      run: |
        cat ~/.docker/config.json

    # Install dependencies and run tests
    - name: 'Install dependencies and run tests'
      run: |
        npm install
        npm test

    # Build Docker image
    - name: 'Build Docker image'
      run: |
        docker build -t gcr.io/${{ secrets.GCLOUD_PROJECT }}/assignment-app .

    # Push Docker image to Google Container Registry
    - name: 'Push Docker image to GCR'
      run: |
        docker push gcr.io/${{ secrets.GCLOUD_PROJECT }}/assignment-app

    # Deploy to Cloud Run
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy assignment-app \
          --image gcr.io/${{ secrets.GCLOUD_PROJECT }}/assignment-app \
          --platform managed \
          --region ${{ secrets.GCR_REGION }} \
          --allow-unauthenticated \
          --set-env-vars NODE_ENV=production