name: Build and Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3
    
    # Authenticate with Google Cloud
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

    # Setup Google Cloud SDK
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCLOUD_PROJECT }}

    # Verify Active Account (Check if the correct account is active)
    - name: Verify Active Account
      run: |
        gcloud auth list

    - name: Authenticate Docker with Google Cloud
      run: |
        gcloud auth configure-docker ${{ secrets.GCR_REGION }}-docker.pkg.dev

    # Debug Docker Authentication    
    - name: Debug Docker Authentication
      run: |
        cat ~/.docker/config.json
    
    - name: Verify GCR Authentication
      run: |
        gcloud container images list --repository=gcr.io/${{ secrets.GCLOUD_PROJECT }}
      

    # Install dependencies and run tests
    - name: 'Install dependencies and run tests'
      run: |
        npm install
        npm test

    # Build Docker image
    - name: 'Build Docker image'
      run: |
        docker build -t ${{ secrets.GCR_REGION }}-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT }}/gcr.io/assignment-app .

    # Push Docker image to Artifact Registry
    - name: 'Push Docker image to Artifact Registry'
      run: |
        docker push ${{ secrets.GCR_REGION }}-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT }}/gcr.io/assignment-app


    # Deploy to Cloud Run
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy assignment-app \
          --image ${{ secrets.GCR_REGION }}-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT }}/gcr.io/assignment-app \
          --platform managed \
          --region ${{ secrets.GCR_REGION }} \
          --allow-unauthenticated \
          --set-env-vars NODE_ENV=production